<?php
/**
 * ContributorsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API V2
 *
 * Connect your software to POEditor with this simple API
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * ContributorsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContributorsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'contributorsAddPost' => [
            'application/x-www-form-urlencoded',
        ],
        'contributorsListPost' => [
            'application/x-www-form-urlencoded',
        ],
        'contributorsRemovePost' => [
            'application/x-www-form-urlencoded',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation contributorsAddPost
     *
     * Adds a contributor to a project language or an administrator to a project.
     *
     * @param  string $api_token api_token (required)
     * @param  string $id The id of project (required)
     * @param  string $name The name of contributor (required)
     * @param  string $email The email of contributor (required)
     * @param  string $language The language code (Required if adding a contributor) (optional)
     * @param  int $admin Set it to 1 for adding as administrator (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsAddPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Response
     */
    public function contributorsAddPost($api_token, $id, $name, $email, $language = null, $admin = null, string $contentType = self::contentTypes['contributorsAddPost'][0])
    {
        list($response) = $this->contributorsAddPostWithHttpInfo($api_token, $id, $name, $email, $language, $admin, $contentType);
        return $response;
    }

    /**
     * Operation contributorsAddPostWithHttpInfo
     *
     * Adds a contributor to a project language or an administrator to a project.
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (required)
     * @param  string $name The name of contributor (required)
     * @param  string $email The email of contributor (required)
     * @param  string $language The language code (Required if adding a contributor) (optional)
     * @param  int $admin Set it to 1 for adding as administrator (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsAddPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function contributorsAddPostWithHttpInfo($api_token, $id, $name, $email, $language = null, $admin = null, string $contentType = self::contentTypes['contributorsAddPost'][0])
    {
        $request = $this->contributorsAddPostRequest($api_token, $id, $name, $email, $language, $admin, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation contributorsAddPostAsync
     *
     * Adds a contributor to a project language or an administrator to a project.
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (required)
     * @param  string $name The name of contributor (required)
     * @param  string $email The email of contributor (required)
     * @param  string $language The language code (Required if adding a contributor) (optional)
     * @param  int $admin Set it to 1 for adding as administrator (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsAddPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contributorsAddPostAsync($api_token, $id, $name, $email, $language = null, $admin = null, string $contentType = self::contentTypes['contributorsAddPost'][0])
    {
        return $this->contributorsAddPostAsyncWithHttpInfo($api_token, $id, $name, $email, $language, $admin, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contributorsAddPostAsyncWithHttpInfo
     *
     * Adds a contributor to a project language or an administrator to a project.
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (required)
     * @param  string $name The name of contributor (required)
     * @param  string $email The email of contributor (required)
     * @param  string $language The language code (Required if adding a contributor) (optional)
     * @param  int $admin Set it to 1 for adding as administrator (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsAddPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contributorsAddPostAsyncWithHttpInfo($api_token, $id, $name, $email, $language = null, $admin = null, string $contentType = self::contentTypes['contributorsAddPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Response';
        $request = $this->contributorsAddPostRequest($api_token, $id, $name, $email, $language, $admin, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contributorsAddPost'
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (required)
     * @param  string $name The name of contributor (required)
     * @param  string $email The email of contributor (required)
     * @param  string $language The language code (Required if adding a contributor) (optional)
     * @param  int $admin Set it to 1 for adding as administrator (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsAddPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contributorsAddPostRequest($api_token, $id, $name, $email, $language = null, $admin = null, string $contentType = self::contentTypes['contributorsAddPost'][0])
    {

        // verify the required parameter 'api_token' is set
        if ($api_token === null || (is_array($api_token) && count($api_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_token when calling contributorsAddPost'
            );
        }

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling contributorsAddPost'
            );
        }

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling contributorsAddPost'
            );
        }

        // verify the required parameter 'email' is set
        if ($email === null || (is_array($email) && count($email) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $email when calling contributorsAddPost'
            );
        }




        $resourcePath = '/contributors/add';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($api_token !== null) {
            $formParams['api_token'] = ObjectSerializer::toFormValue($api_token);
        }
        // form params
        if ($id !== null) {
            $formParams['id'] = ObjectSerializer::toFormValue($id);
        }
        // form params
        if ($name !== null) {
            $formParams['name'] = ObjectSerializer::toFormValue($name);
        }
        // form params
        if ($email !== null) {
            $formParams['email'] = ObjectSerializer::toFormValue($email);
        }
        // form params
        if ($language !== null) {
            $formParams['language'] = ObjectSerializer::toFormValue($language);
        }
        // form params
        if ($admin !== null) {
            $formParams['admin'] = ObjectSerializer::toFormValue($admin);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation contributorsListPost
     *
     * Returns the list of contributors from your projects.
     *
     * @param  string $api_token api_token (required)
     * @param  string $id The id of project (Optional, unless language is set. Then, it becomes required) (optional)
     * @param  string $language The language code (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsListPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ContributorsListResponse
     */
    public function contributorsListPost($api_token, $id = null, $language = null, string $contentType = self::contentTypes['contributorsListPost'][0])
    {
        list($response) = $this->contributorsListPostWithHttpInfo($api_token, $id, $language, $contentType);
        return $response;
    }

    /**
     * Operation contributorsListPostWithHttpInfo
     *
     * Returns the list of contributors from your projects.
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (Optional, unless language is set. Then, it becomes required) (optional)
     * @param  string $language The language code (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsListPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ContributorsListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function contributorsListPostWithHttpInfo($api_token, $id = null, $language = null, string $contentType = self::contentTypes['contributorsListPost'][0])
    {
        $request = $this->contributorsListPostRequest($api_token, $id, $language, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ContributorsListResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\ContributorsListResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ContributorsListResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ContributorsListResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ContributorsListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation contributorsListPostAsync
     *
     * Returns the list of contributors from your projects.
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (Optional, unless language is set. Then, it becomes required) (optional)
     * @param  string $language The language code (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsListPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contributorsListPostAsync($api_token, $id = null, $language = null, string $contentType = self::contentTypes['contributorsListPost'][0])
    {
        return $this->contributorsListPostAsyncWithHttpInfo($api_token, $id, $language, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contributorsListPostAsyncWithHttpInfo
     *
     * Returns the list of contributors from your projects.
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (Optional, unless language is set. Then, it becomes required) (optional)
     * @param  string $language The language code (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsListPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contributorsListPostAsyncWithHttpInfo($api_token, $id = null, $language = null, string $contentType = self::contentTypes['contributorsListPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ContributorsListResponse';
        $request = $this->contributorsListPostRequest($api_token, $id, $language, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contributorsListPost'
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (Optional, unless language is set. Then, it becomes required) (optional)
     * @param  string $language The language code (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsListPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contributorsListPostRequest($api_token, $id = null, $language = null, string $contentType = self::contentTypes['contributorsListPost'][0])
    {

        // verify the required parameter 'api_token' is set
        if ($api_token === null || (is_array($api_token) && count($api_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_token when calling contributorsListPost'
            );
        }




        $resourcePath = '/contributors/list';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($api_token !== null) {
            $formParams['api_token'] = ObjectSerializer::toFormValue($api_token);
        }
        // form params
        if ($id !== null) {
            $formParams['id'] = ObjectSerializer::toFormValue($id);
        }
        // form params
        if ($language !== null) {
            $formParams['language'] = ObjectSerializer::toFormValue($language);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation contributorsRemovePost
     *
     * Removes a contributor from a project language or an admin from a project, if the language is not specified.
     *
     * @param  string $api_token api_token (required)
     * @param  string $id The id of project (required)
     * @param  string $email The email of contributor (required)
     * @param  string $language The language code (Required if removing a contributor from a certain language) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsRemovePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\Response
     */
    public function contributorsRemovePost($api_token, $id, $email, $language = null, string $contentType = self::contentTypes['contributorsRemovePost'][0])
    {
        list($response) = $this->contributorsRemovePostWithHttpInfo($api_token, $id, $email, $language, $contentType);
        return $response;
    }

    /**
     * Operation contributorsRemovePostWithHttpInfo
     *
     * Removes a contributor from a project language or an admin from a project, if the language is not specified.
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (required)
     * @param  string $email The email of contributor (required)
     * @param  string $language The language code (Required if removing a contributor from a certain language) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsRemovePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function contributorsRemovePostWithHttpInfo($api_token, $id, $email, $language = null, string $contentType = self::contentTypes['contributorsRemovePost'][0])
    {
        $request = $this->contributorsRemovePostRequest($api_token, $id, $email, $language, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation contributorsRemovePostAsync
     *
     * Removes a contributor from a project language or an admin from a project, if the language is not specified.
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (required)
     * @param  string $email The email of contributor (required)
     * @param  string $language The language code (Required if removing a contributor from a certain language) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsRemovePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contributorsRemovePostAsync($api_token, $id, $email, $language = null, string $contentType = self::contentTypes['contributorsRemovePost'][0])
    {
        return $this->contributorsRemovePostAsyncWithHttpInfo($api_token, $id, $email, $language, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contributorsRemovePostAsyncWithHttpInfo
     *
     * Removes a contributor from a project language or an admin from a project, if the language is not specified.
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (required)
     * @param  string $email The email of contributor (required)
     * @param  string $language The language code (Required if removing a contributor from a certain language) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsRemovePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contributorsRemovePostAsyncWithHttpInfo($api_token, $id, $email, $language = null, string $contentType = self::contentTypes['contributorsRemovePost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\Response';
        $request = $this->contributorsRemovePostRequest($api_token, $id, $email, $language, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contributorsRemovePost'
     *
     * @param  string $api_token (required)
     * @param  string $id The id of project (required)
     * @param  string $email The email of contributor (required)
     * @param  string $language The language code (Required if removing a contributor from a certain language) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contributorsRemovePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contributorsRemovePostRequest($api_token, $id, $email, $language = null, string $contentType = self::contentTypes['contributorsRemovePost'][0])
    {

        // verify the required parameter 'api_token' is set
        if ($api_token === null || (is_array($api_token) && count($api_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_token when calling contributorsRemovePost'
            );
        }

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling contributorsRemovePost'
            );
        }

        // verify the required parameter 'email' is set
        if ($email === null || (is_array($email) && count($email) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $email when calling contributorsRemovePost'
            );
        }



        $resourcePath = '/contributors/remove';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        if ($api_token !== null) {
            $formParams['api_token'] = ObjectSerializer::toFormValue($api_token);
        }
        // form params
        if ($id !== null) {
            $formParams['id'] = ObjectSerializer::toFormValue($id);
        }
        // form params
        if ($email !== null) {
            $formParams['email'] = ObjectSerializer::toFormValue($email);
        }
        // form params
        if ($language !== null) {
            $formParams['language'] = ObjectSerializer::toFormValue($language);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
